[versions]
mockito = "3.11.2"
hilt = "2.44.2"

[libraries]
mockito-core = {module = "org.mockito:mockito-core" , version.ref = "mockito"}
mockito-android = {module = "org.mockito:mockito-android", version.ref = "mockito"}
hilt-android = {module = "com.google.dagger:hilt-android" , version.ref = "hilt"}
hilt-compiler = {module = "com.google.dagger:hilt-android-compiler" , version.ref = "hilt"}